/*
 * Import transactions from CSV generated by OP's online bank.
 */

'use strict';

var _        = require('underscore');
var csvParse = require('csv-parse');
var Q        = require('q');

var importerHelper = require('./importerHelper');

var generatePayeeProperty = function (record) {
    var explanationField = record[4].trim();

    if (explanationField === 'AUTOMAATTINOSTO') {
        return 'Automaattinosto';
    }

    return record[5];
};

var generateMemoProperty = function (record) {
    var explanationField = record[4].trim();
    var messageField = record[8].trim();

    if (explanationField === 'PKORTTIMAKSU') {
        return null; // No memo needed for card payments
    }

    messageField = messageField.replace(/^Viesti: /, '');

    return messageField.length > 0 ? messageField : null;
};

var generateTransaction = function (record) {
    /*
     * CSV field reference:
     *
     * 'Kirjauspäivä', 'Arvopäivä', 'Määrä  EUROA', 'Laji', 'Selitys', 'Saaja/Maksaja',
     * 'Saajan tilinumero ja pankin BIC', 'Viite', 'Viesti', 'Arkistointitunnus'
     */

    if (!_.isArray(record) || record.length < 10) {
        return null;
    }

    var transaction = {};

    transaction.date = importerHelper.parseDate(record[0]);
    transaction.dateStr = importerHelper.dateToString(transaction.date);

    transaction.payee = generatePayeeProperty(record);

    transaction.amount = importerHelper.parseAmount(record[2]);
    transaction.amountStr = (transaction.amount ? transaction.amount.toFixed(2) : null);

    transaction.targetAccountDescription = record[6];

    // Categorization is handled outside of the importer
    transaction.category = null;

    // TODO: Should we append memo to payee field so that it shows up in GnuCash?
    transaction.memo = generateMemoProperty(record);

    if (!transaction.date || !transaction.dateStr || !transaction.amount || !transaction.amountStr) {
        return null;
    }

    return transaction;
};

var isSupportedFile = function (fileContent) {
    var expectedHeader =
        'Kirjauspäivä;Arvopäivä;Määrä. EUROA;Laji;Selitys;Saaja/Maksaja;Saajan tilinumero ja pankin BIC;Viite;Viesti;Arkistointitunnus';
    var re = new RegExp(expectedHeader);

    if (typeof(fileContent) === 'string') {
        // The header line may or may not contain quotes, so remove all of them before matching
        fileContent = fileContent.replace(/"/g, '');
        return !!fileContent.match(re);
    }

    return false;
};

var importTransactions = function (fileContent) {
    var deferred = Q.defer();
    var transactions = [];

    if (!this.isSupportedFile(fileContent)) {
        deferred.reject(new Error('Input file not recognized as an OP file'));
        return deferred.promise;
    }

    csvParse(fileContent, {delimiter: ';'}, function (err, data) {
        var success = _.every(data, function (record, index) {
            if (index === 0 || record.length === 1) {
                return true; // Skip the header and empty lines
            }

            var transaction = generateTransaction(record);
            if (!transaction) {
                deferred.reject(new Error('Corrupted content in OP input file'));
                return false;
            }

            transactions.push(transaction);
            return true;
        }, this);

        if (success) {
            deferred.resolve(transactions);
        }
    });

    return deferred.promise;
};

module.exports = {
    isSupportedFile: isSupportedFile,
    importTransactions: importTransactions
};
